version: '3'

services:
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'
  web:
    build: .
    command: bash -c "python /newsfeed/manage.py migrate --noinput && python /newsfeed/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/newsfeed
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A newsfeed worker -l info
    volumes:
      - .:/newsfeed
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A newsfeed beat -l info
    volumes:
      - .:/newsfeed
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redisdata: