# Generated by Django 2.2.7 on 2021-03-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publishedAt']},
        ),
    ]
