# Generated by Django 2.2.7 on 2021-03-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
