# Generated by Django 2.2.7 on 2021-03-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsnotification',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
