# Generated by Django 2.2.7 on 2021-03-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210321_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsnotification',
            name='news',
        ),
        migrations.AddField(
            model_name='newsnotification',
            name='news_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
