# Generated by Django 2.2.7 on 2021-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210319_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernewssetting',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usernewssetting',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usernewssetting',
            name='news_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
