# Generated by Django 2.2.7 on 2021-03-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210319_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernewssetting',
            old_name='country',
            new_name='countries',
        ),
    ]
